USE [master]
GO

/****** Object:  Database [dbCovidFineSystem]    Script Date: 29/11/2021 5:39:10 PM ******/
CREATE DATABASE [dbCovidFineSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbCovidFineSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\dbCovidFineSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbCovidFineSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\dbCovidFineSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [dbCovidFineSystem] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbCovidFineSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbCovidFineSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbCovidFineSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbCovidFineSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbCovidFineSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbCovidFineSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbCovidFineSystem] SET  MULTI_USER 
GO

ALTER DATABASE [dbCovidFineSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbCovidFineSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbCovidFineSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbCovidFineSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbCovidFineSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbCovidFineSystem] SET QUERY_STORE = OFF
GO

USE [dbCovidFineSystem]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [dbCovidFineSystem] SET  READ_WRITE 
GO

